#!/usr/bin/env python3
"""Fetch the channel glyphs from Lucide (ISC) and write them as Android vector drawables.

Run from the repo root: python3 ui/design/tools/lucide.py
Outputs ui/design/src/main/res/drawable/ic_glyph_<name>.xml and ui/design/.../Glyphs.kt.
Lucide's license is reproduced in THIRD_PARTY_NOTICES.md; keep it in step with VERSION.
"""
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

VERSION = "1.54.0"
# Lucide name -> label shown in the editor. Keep this list short; it is a palette, not a catalog.
GLYPHS = [
    ("tv", "TV"), ("film", "Film"), ("clapperboard", "Movies"), ("laugh", "Comedy"), ("drama", "Drama"),
    ("ghost", "Horror"), ("rocket", "Sci-fi"), ("swords", "Action"), ("heart", "Romance"), ("baby", "Kids"),
    ("music", "Music"), ("trophy", "Sports"), ("newspaper", "News"), ("globe", "World"), ("sparkles", "Magic"),
    ("star", "Star"), ("popcorn", "Popcorn"), ("flame", "Hot"), ("cat", "Cat"), ("dog", "Dog"),
    ("car", "Cars"), ("gamepad-2", "Games"), ("mic", "Talk"), ("palette", "Art"), ("book-open", "Stories"),
    ("camera", "Camera"), ("radio", "Radio"), ("zap", "Zap"), ("skull", "Skull"), ("wand-sparkles", "Wand"),
    ("sun", "Day"), ("moon", "Night"), ("history", "Retro"), ("tent", "Outdoors"), ("compass", "Travel"),
    ("mountain", "Nature"),
]
ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "ui/design/src/main/res/drawable"
KT = ROOT / "ui/design/src/main/kotlin/net/clickarr/ui/design/Glyphs.kt"
NS = "{http://www.w3.org/2000/svg}"


def fetch(name: str) -> str:
    url = f"https://unpkg.com/lucide-static@{VERSION}/icons/{name}.svg"
    with urllib.request.urlopen(url) as r:
        return r.read().decode()


def num(v: str) -> float:
    return float(v)


def fmt(v: float) -> str:
    return ("%.3f" % v).rstrip("0").rstrip(".")


def element_path(el) -> str:
    tag = el.tag.replace(NS, "")
    a = el.attrib
    if tag == "path":
        return a["d"]
    if tag == "line":
        return f"M{a['x1']},{a['y1']} L{a['x2']},{a['y2']}"
    if tag in ("polyline", "polygon"):
        pts = re.findall(r"-?\d*\.?\d+", a["points"])
        pairs = [f"{pts[i]},{pts[i + 1]}" for i in range(0, len(pts), 2)]
        d = "M" + " L".join(pairs)
        return d + " Z" if tag == "polygon" else d
    if tag == "circle":
        cx, cy, r = num(a["cx"]), num(a["cy"]), num(a["r"])
        return f"M{fmt(cx - r)},{fmt(cy)} A{fmt(r)},{fmt(r)} 0 1 0 {fmt(cx + r)},{fmt(cy)} A{fmt(r)},{fmt(r)} 0 1 0 {fmt(cx - r)},{fmt(cy)} Z"
    if tag == "ellipse":
        cx, cy, rx, ry = num(a["cx"]), num(a["cy"]), num(a["rx"]), num(a["ry"])
        return f"M{fmt(cx - rx)},{fmt(cy)} A{fmt(rx)},{fmt(ry)} 0 1 0 {fmt(cx + rx)},{fmt(cy)} A{fmt(rx)},{fmt(ry)} 0 1 0 {fmt(cx - rx)},{fmt(cy)} Z"
    if tag == "rect":
        x, y, w, h = num(a.get("x", "0")), num(a.get("y", "0")), num(a["width"]), num(a["height"])
        rx = num(a.get("rx", "0"))
        ry = num(a.get("ry", str(rx)))
        if rx == 0 and ry == 0:
            return f"M{fmt(x)},{fmt(y)} H{fmt(x + w)} V{fmt(y + h)} H{fmt(x)} Z"
        return (
            f"M{fmt(x + rx)},{fmt(y)} H{fmt(x + w - rx)} A{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(x + w)},{fmt(y + ry)}"
            f" V{fmt(y + h - ry)} A{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(x + w - rx)},{fmt(y + h)} H{fmt(x + rx)}"
            f" A{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(x)},{fmt(y + h - ry)} V{fmt(y + ry)} A{fmt(rx)},{fmt(ry)} 0 0 1 {fmt(x + rx)},{fmt(y)} Z"
        )
    raise SystemExit(f"unsupported element <{tag}>")


def drawable(name: str, svg: str) -> str:
    root = ET.fromstring(svg)
    paths = [element_path(el) for el in root.iter() if el is not root and el.tag.replace(NS, "") != "title"]
    body = "\n".join(
        f'    <path android:pathData="{d}" android:strokeColor="#FFFFFFFF" android:strokeWidth="2"\n'
        f'        android:strokeLineCap="round" android:strokeLineJoin="round" android:fillColor="#00000000" />'
        for d in paths
    )
    return (
        f"<!-- Lucide '{name}' v{VERSION}, ISC license (see THIRD_PARTY_NOTICES.md). Generated by ui/design/tools/lucide.py. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">\n'
        f"{body}\n</vector>\n"
    )


def kotlin() -> str:
    entries = ",\n".join(f'    Glyph("{n}", "{label}", R.drawable.ic_glyph_{n.replace("-", "_")})' for n, label in GLYPHS)
    return (
        "package net.clickarr.ui.design\n\n"
        "/** A channel glyph: Lucide name, label for the picker, drawable. Generated by ui/design/tools/lucide.py. */\n"
        "data class Glyph(val name: String, val label: String, val res: Int)\n\n"
        "/** The channel icon palette (design language 1.6: Lucide, 2 dp stroke, never filled). */\n"
        "object ClickarrGlyphs {\n"
        "    val all: List<Glyph> = listOf(\n"
        f"{entries},\n"
        "    )\n\n"
        "    fun byName(name: String): Glyph? = all.firstOrNull { it.name == name }\n"
        "}\n"
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, _ in GLYPHS:
        svg = fetch(name)
        (OUT / f"ic_glyph_{name.replace('-', '_')}.xml").write_text(drawable(name, svg))
        print("wrote", name, file=sys.stderr)
    KT.write_text(kotlin())


if __name__ == "__main__":
    main()
