package net.clickarr.ui.design

/** A channel glyph: Lucide name, label for the picker, drawable. Generated by ui/design/tools/lucide.py. */
data class Glyph(val name: String, val label: String, val res: Int)

/** The channel icon palette (design language 1.6: Lucide, 2 dp stroke, never filled). */
object ClickarrGlyphs {
    val all: List<Glyph> = listOf(
    Glyph("tv", "TV", R.drawable.ic_glyph_tv),
    Glyph("film", "Film", R.drawable.ic_glyph_film),
    Glyph("clapperboard", "Movies", R.drawable.ic_glyph_clapperboard),
    Glyph("laugh", "Comedy", R.drawable.ic_glyph_laugh),
    Glyph("drama", "Drama", R.drawable.ic_glyph_drama),
    Glyph("ghost", "Horror", R.drawable.ic_glyph_ghost),
    Glyph("rocket", "Sci-fi", R.drawable.ic_glyph_rocket),
    Glyph("swords", "Action", R.drawable.ic_glyph_swords),
    Glyph("heart", "Romance", R.drawable.ic_glyph_heart),
    Glyph("baby", "Kids", R.drawable.ic_glyph_baby),
    Glyph("music", "Music", R.drawable.ic_glyph_music),
    Glyph("trophy", "Sports", R.drawable.ic_glyph_trophy),
    Glyph("newspaper", "News", R.drawable.ic_glyph_newspaper),
    Glyph("globe", "World", R.drawable.ic_glyph_globe),
    Glyph("sparkles", "Magic", R.drawable.ic_glyph_sparkles),
    Glyph("star", "Star", R.drawable.ic_glyph_star),
    Glyph("popcorn", "Popcorn", R.drawable.ic_glyph_popcorn),
    Glyph("flame", "Hot", R.drawable.ic_glyph_flame),
    Glyph("cat", "Cat", R.drawable.ic_glyph_cat),
    Glyph("dog", "Dog", R.drawable.ic_glyph_dog),
    Glyph("car", "Cars", R.drawable.ic_glyph_car),
    Glyph("gamepad-2", "Games", R.drawable.ic_glyph_gamepad_2),
    Glyph("mic", "Talk", R.drawable.ic_glyph_mic),
    Glyph("palette", "Art", R.drawable.ic_glyph_palette),
    Glyph("book-open", "Stories", R.drawable.ic_glyph_book_open),
    Glyph("camera", "Camera", R.drawable.ic_glyph_camera),
    Glyph("radio", "Radio", R.drawable.ic_glyph_radio),
    Glyph("zap", "Zap", R.drawable.ic_glyph_zap),
    Glyph("skull", "Skull", R.drawable.ic_glyph_skull),
    Glyph("wand-sparkles", "Wand", R.drawable.ic_glyph_wand_sparkles),
    Glyph("sun", "Day", R.drawable.ic_glyph_sun),
    Glyph("moon", "Night", R.drawable.ic_glyph_moon),
    Glyph("history", "Retro", R.drawable.ic_glyph_history),
    Glyph("tent", "Outdoors", R.drawable.ic_glyph_tent),
    Glyph("compass", "Travel", R.drawable.ic_glyph_compass),
    Glyph("mountain", "Nature", R.drawable.ic_glyph_mountain),
    )

    fun byName(name: String): Glyph? = all.firstOrNull { it.name == name }
}
